# Variables

@baseUrl = http://localhost:3333


# Health
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Room 2",
  "description": "Description 1"
}

###

@roomId = {{createRoom.response.body.$.id}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/room/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/room/9fef93fa-4903-45b1-a193-3ac0dae3cc4d/questions
Content-Type: application/json

{
  "question": "Quantos anos ele tem?"
}

### 